name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim: ["devel", "stable"]

    name: Nim ${{ matrix.nim }}
    steps:
      - name: Setup Nim Enviroment
        uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}

      - name: Run Tests
        run: nimble test

      - name: Test doc examples
        run: nimble checkDocs

  deploy:
    needs: test
    permissions:
      pages: write # To deploy to Pages
      id-token: write # Verify deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: "Setup nim"
        uses: jiro4989/setup-nim-action@v1

      - name: "Build documentation"
        uses: ire4ever1190/nim-docs-action@v1
        with:
          main-file: "src/bencodie.nim"
          deploy: "pages"
